CONTRIBUTING.md
=> Add contributors to the README

CONTRIBUTING.md, README.md
=> move contributors to README

multimodal-understanding/workshop/README.md
=> mm workshop readme

multimodal-understanding/workshop/4.3_invoke_agent.ipynb
=> fix 4.3_invoke_agent.ipynb

multimodal-understanding/repeatable-patterns/11-pydantic-tool-calling/pydantic_tool_calling.ipynb
Add function and examples for calling the converse API with pydantic tools
=> Pydantic tool calling with converse API

multimodal-understanding/workshop/01_Getting Started with Nova Models.ipynb
The system_message arg is defined in several cells but then not used to call call_nova. I added it to the calls.
=> Added missing system_message argument in call_nova calls

multimodal-understanding/repeatable-patterns/12-smolagents-and-litellm/README.md, multimodal-understanding/repeatable-patterns/12-smolagents-and-litellm/smolagents_and_litellm.ipynb
Adding sample code with HF smolagents and litellm.
Adding sample code with HF smolagents and litellm.
=> Adding sample code with smolagents and litellm

multimodal-understanding/workshop/1-getting-started.ipynb
Temporarily removing doc understanding from workshop till fix is in
=> Remove document understanding from workshop

speech-to-speech/repeatable-patterns/langchain-knowledge-base/nova_sonic_tool_use.py
unused imports are cleaned up.
=> unused imports cleaned up

speech-to-speech/README.md
=> add readme file

speech-to-speech/sample-codes/console-python/README.md
=> include test instruction

multimodal-generation/repeatable-patterns/02-video-replication/01_video_replication_basic.ipynb, multimodal-generation/repeatable-patterns/02-video-replication/README.md
*Issue #, if available:* N/A
*Description of changes:* This notebook demonstrates how to replicate video content using Amazon Nova Canvas and Amazon Nova Reel on Amazon Bedrock
=> Add video replication notebook

speech-to-speech/sample-codes/websocket-nodejs/public/src/main.js
… device and audiocontext
https://github.com/aws-samples/amazon-nova-samples/issues/78 
This fixes the [firefox issue](https://github.com/prettyprettyprettygood/amazon-nova-samples/issues/10) where the mismatched sample rates between the Audiocontext and input source throws and error and crashes the app
This fix allows firefox to use default system provided sample rate and programmatically down sample it to the model specific input config sample rate.
NOTE: This doesn't impact the existing behavior for Chrome browser as the sampling process is automatically done for Chromium based browsers as part of the `AudioContext` and hence the sampling ratio is alway 1 for such browsers.
Testing:
`npm run build` and `num start` the app, load the url …
=> firefox browser fix for sample rate incompatibility between usermedia and audiocontext

multimodal-understanding/repeatable-patterns/03-synthetic-data-knowledge-distillation/README.md, multimodal-understanding/repeatable-patterns/03-synthetic-data-knowledge-distillation/synthetic_data_distillation_fine_tuning.ipynb, multimodal-understanding/repeatable-patterns/03-synthetic-data-knowledge-distillation/template.json
Modified readme, and notebook to reflect nova premier as teacher model. Updated system prompt in template.json.
=> Update the distillation code to use Nova Premier as teacher model

multimodal-understanding/getting-started/README.md
=> Add Nova Premier in Readme

multimodal-understanding/repeatable-patterns/25-temporal-reasoning-premier/25-temporal-reasoning-premier.ipynb
- Notebook for Amazon Nova Premier temporal understanding tasks with video
- Test video (Meridian_Clip.mp4) for users to download and test the notebook with. The video is a clip from Netflix Open Content and approved for public use
=> Nova Premier temporal understanding notebook and video file needed

speech-to-speech/sample-codes/websocket-java/ui-stream/package-lock.json, speech-to-speech/sample-codes/websocket-java/ui-stream/package.json
Bump version of `vite` to suppress the noise of transitive dependency during `npm audit`
=> Chore: Update Javascript dependencies

multimodal-understanding/workshop/1-getting-started.ipynb, multimodal-understanding/workshop/3-rag-knowledge-bases.ipynb
=> mm understanding workshop

speech-to-speech/sample-codes/websocket-java/app/src/main/java/org/example/utility/OutputEventsInteractObserver.java, speech-to-speech/sample-codes/websocket-java/app/src/main/java/org/example/utility/ToolResultProcessor.java
- Refactored tool call handling to use non-blocking asynchronous execution with CompletableFuture to prevent blocking the main event processing thread.
- Created a dedicated ToolResultProcessor class to handle tool execution asynchronously
=> Implement async tool processing with CompletableFuture

speech-to-speech/sample-codes/websocket-nodejs/README.md, speech-to-speech/sample-codes/websocket-nodejs/package-lock.json, speech-to-speech/sample-codes/websocket-nodejs/package.json, speech-to-speech/sample-codes/websocket-nodejs/src/client.ts
Fixes: https://github.com/aws-samples/amazon-nova-samples/issues/139
Replaces axios with Node.js native fetch.
Verified that websocket-nodejs example is working.
=> chore(websocket-nodejs): replace axios with Node.js native fetch

speech-to-speech/repeatable-patterns/bedrock-knowledge-base/README.md, speech-to-speech/repeatable-patterns/bedrock-knowledge-base/package-lock.json, speech-to-speech/repeatable-patterns/bedrock-knowledge-base/package.json, speech-to-speech/repeatable-patterns/customer-service/hotel-cancellation-websocket/README.md, speech-to-speech/repeatable-patterns/customer-service/hotel-cancellation-websocket/package-lock.json, speech-to-speech/repeatable-patterns/customer-service/hotel-cancellation-websocket/package.json, speech-to-speech/repeatable-patterns/customer-service/package-lock.json, speech-to-speech/repeatable-patterns/resume-conversation/README.md, speech-to-speech/repeatable-patterns/resume-conversation/package-lock.json, speech-to-speech/repeatable-patterns/resume-conversation/package.json, speech-to-speech/workshops/react-client/package.json
Noticed in https://github.com/aws-samples/amazon-nova-samples/issues/139
Removed axios dependency from package.json files where it's not used.
=> chore(deps): remove unused axios dependency

multimodal-understanding/repeatable-patterns/26-nova-citations/nova_client.py
Updating to leverage builtin boto3 config.
=> Leveraging boto3 built-in retry instead of custom implementation

multimodal-understanding/repeatable-patterns/31-nova-stream-parser/.gitignore, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/NovaStreamParser/constants.py, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/NovaStreamParser/helpers.py, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/NovaStreamParser/nova_event_stream.py, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/NovaStreamParser/nova_parsed_event_stream.py, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/NovaStreamParser/nova_response_parser.py, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/NovaStreamParser/nova_response_stream_handler.py, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/NovaStreamParser_Tutorial.ipynb, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/README.md, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/pyproject.toml, multimodal-understanding/repeatable-patterns/31-nova-stream-parser/sample_usage.py
Initial commit - NovaStreamParser
Utility module for removing of <thinking> tags (or any other tags) from Nova model streaming results.
=> NovaStreamParser

.gitignore, speech-to-speech/workshops/react-client/src/s2s.css, speech-to-speech/workshops/react-client/src/s2s.js
The conversation box now automatically scrolls to the bottom whenever new messages are added, providing a seamless chat experience.
=> The conversation box now automatically scrolls to the bottom
